#!/bin/sh

sed -i '/coremark/d' /etc/crontabs/root
echo "#0 4 * * * /etc/coremark.sh" >> /etc/crontabs/root
echo "*/5 * * * * /usr/bin/rockchip-pwm-fan.sh start >/dev/null 2>&1" >> /etc/crontabs/root
crontab /etc/crontabs/root

touch /etc/bench.log
